collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6612903
color:
  saturation: 0.7114695
  brandStrength: 0.4767025
  lightness: 0.2043011
  brandColors:
    - '#0B0E0F'
    - '#49C500'
    - '#FAFCFC'
    - '#999A9A'
    - '#0D1FA3'
  rhythmicContrast: 0.9892473
layout_spectrum: 0.2903226
name: Arbcore Ltd
